Уровень 2
N1trog3N/Workshop_OOP_Project pull request #2
Opened 2022-04-10 19:28 UTC by N1trog3N

Добавлено всё необходимое для перехода на уровень 2.

2022-04-11 23:24 UTC, DenVilk requested changes
В целом все хорошо. Запросил изменения ниже.

2022-04-11 23:24 UTC, DenVilk commented on workshop.py
> +            new_receipt = receipt.Receipt(dev, dateofreceive, dateofrepair, initials, status)
В каждом условии повторяются две строчки, вынеси их за условия.

2022-04-12 13:39 UTC, N1trog3N commented
Пофиксил

2022-04-12 14:23 UTC, DenVilk approved these changes
Допущен к третьему уровню.

2022-04-14 07:31 UTC, merged